/* =========================================================================
   MILEAGE — seed data
   This is the ONLY file you need to edit to keep the site current.
   Everything below is plain data. Add, remove, or change entries freely.
   ========================================================================= */

window.DATA = {

  // Platforms shown as badges. tone drives the dot colour (video/image/text).
  platforms: {
    higgsfield: { label: "Higgsfield", kind: "AI video & image", tone: "video" },
    magnific:   { label: "Magnific",   kind: "Upscale & enhance (Freepik)", tone: "image" },
    claude:     { label: "Claude",     kind: "Reasoning · writing · code", tone: "text" },
    chatgpt:    { label: "ChatGPT",    kind: "Assistant · reasoning · images", tone: "text" },
  },

  // TOOL PICKER — use case -> recommendation. cost: 1 low / 2 med / 3 high.
  picker: [
    { cat:"Video", task:"Short social video (Reel / TikTok / Short)", plat:"higgsfield",
      pick:"720p · 5s · low–med motion preset", cost:1,
      why:"Platforms re-compress vertical video hard. 1080p and 10s mostly buy credits you can't see on a phone." },
    { cat:"Video", task:"Cinematic b-roll / establishing shot", plat:"higgsfield",
      pick:"Camera-move preset · higher steps · 1080p", cost:3,
      why:"Here the resolution and a deliberate camera move actually show. Worth the spend; keep clips to 5s." },
    { cat:"Video", task:"Talking-head / product loop for a landing page", plat:"higgsfield",
      pick:"1080p · static or slow push · 24fps", cost:2,
      why:"Detail matters on desktop, but heavy motion presets cost more and add nothing to a near-static shot." },
    { cat:"Image / Upscale", task:"Upscale a real photo, keep it faithful", plat:"magnific",
      pick:"2x · low Creativity · high Resemblance", cost:1,
      why:"High creativity invents detail and forces re-runs. Faithful upscales are cheaper and need fewer retries." },
    { cat:"Image / Upscale", task:"Reimagine an illustration at higher res", plat:"magnific",
      pick:"4x · high Creativity · med Fractality", cost:3,
      why:"Stylized work is where creativity earns its cost. Going past 4x rarely changes the final crop you ship." },
    { cat:"Image / Upscale", task:"Generate a marketing / hero image", plat:"chatgpt",
      pick:"Image model · 1 reference + tight style words", cost:2,
      why:"A reference image does the work ten adjectives can't, cutting regenerations that quietly burn credits." },
    { cat:"Text / Reasoning", task:"Quick facts, drafting, rephrasing, summaries", plat:"claude",
      pick:"Fast tier (Haiku) — or ChatGPT mini", cost:1,
      why:"Routine text doesn't need a frontier model. The cheap tier is 10-20x less per token for the same result." },
    { cat:"Text / Reasoning", task:"Hard reasoning, math, architecture, tricky bugs", plat:"claude",
      pick:"Top tier (Opus) — or ChatGPT reasoning model", cost:3,
      why:"The one place to pay up. A cheap model that fails sends you into a retry loop that costs more overall." },
    { cat:"Text / Reasoning", task:"Long document analysis / big context", plat:"claude",
      pick:"Balanced tier (Sonnet) · prompt caching on", cost:2,
      why:"Sonnet handles large context well; caching a repeated document stops you re-paying for the same tokens." },
    { cat:"Text / Reasoning", task:"Coding: refactor, tests, everyday changes", plat:"claude",
      pick:"Balanced tier (Sonnet)", cost:2,
      why:"Reserve the top tier for genuinely hard problems. Most coding lands first-try on the balanced tier." },
    { cat:"Text / Reasoning", task:"Bulk generation (many short outputs)", plat:"chatgpt",
      pick:"Mini / fast tier · batch the calls", cost:1,
      why:"Volume multiplies waste. Cheapest capable model + batching is the difference between cents and dollars." },
  ],

  // RECIPES — optimal vs overkill settings. save: 0..1 (share of credits saved vs the wasteful default).
  recipes: [
    { plat:"higgsfield", title:"Social reel",
      optimal:["720p","5s","Motion 0.4-0.6","24 fps"], overkill:["1080p","10s","Max motion","60 fps"], save:0.6,
      note:"Vertical feeds downscale anyway. Spend on a good start frame, not pixels." },
    { plat:"higgsfield", title:"Cinematic shot",
      optimal:["1080p","5s","1 camera move","Higher steps"], overkill:["4K-style upscale","10s","Stacked moves"], save:0.35,
      note:"One clean move reads better than three. Stacking presets multiplies cost and chaos." },
    { plat:"magnific", title:"Faithful photo upscale",
      optimal:["2x","Creativity -1->0","Resemblance high","HDR low"], overkill:["8x-16x","Creativity high","HDR high"], save:0.7,
      note:"High creativity = invented detail = retries. Big factors blow past your real output size." },
    { plat:"magnific", title:"Creative re-render",
      optimal:["4x","Creativity high","Fractality med","Resemblance low"], overkill:["16x","Fractality max"], save:0.45,
      note:"4x covers almost every crop you'll publish. Max fractality adds noise, not usable detail." },
    { plat:"claude", title:"Everyday text task",
      optimal:["Fast tier (Haiku)","Trim context","No verbose preamble"], overkill:["Top tier (Opus)","Paste full history"], save:0.85,
      note:"Model choice dwarfs every other lever. Match the tier to the task's actual difficulty." },
    { plat:"claude", title:"Repeated long context",
      optimal:["Balanced (Sonnet)","Prompt caching ON","Reuse cached doc"], overkill:["Re-paste doc each turn","Top tier by default"], save:0.5,
      note:"Caching stops you re-paying for the same document on every single message." },
    { plat:"chatgpt", title:"Routine assistant use",
      optimal:["Mini / standard tier","One clear instruction"], overkill:["Reasoning model for everything"], save:0.6,
      note:"Reserve reasoning models for problems that genuinely need step-by-step thinking." },
    { plat:"chatgpt", title:"Image generation",
      optimal:["1 reference image","Short style words","Right size once"], overkill:["Prompt-only","Regenerate to fix size"], save:0.4,
      note:"A reference cuts regenerations. Pick the output size up front instead of re-rolling." },
  ],

  // INPUTS — what to feed each platform.
  inputs: [
    { plat:"higgsfield",
      do:["Start from a clean, high-contrast key frame — motion amplifies whatever's already there.",
          "Keep one clear subject; busy backgrounds smear when the camera moves.",
          "Name the camera move in plain words (slow push in, orbit left) rather than stacking presets."],
      dont:["Don't feed a noisy or low-res start frame and expect the model to clean it up.",
            "Don't request long durations to 'get more' — you mostly get more credits spent."] },
    { plat:"magnific",
      do:["Feed the cleanest source you have — artifacts and JPEG noise get magnified, not removed.",
          "Pick the upscale factor from your real target size, not the maximum available.",
          "For faithful work, lean on Resemblance; for re-imagining, lean on Creativity."],
      dont:["Don't upscale an already-upscaled image — errors compound.",
            "Don't max every slider; high Creativity + high HDR often needs several paid retries."] },
    { plat:"claude",
      do:["Give structured context: label sections, use tags/headers so the model finds what matters.",
          "Show one or two examples of the output you want instead of describing it at length.",
          "Cache or reuse long reference material rather than re-pasting it every turn."],
      dont:["Don't paste entire chat histories or whole files when a relevant slice will do.",
            "Don't pad with politeness and preamble — it's tokens in and tokens echoed back."] },
    { plat:"chatgpt",
      do:["Put durable rules in a system / custom-instruction slot so you don't repeat them each message.",
          "For images, attach a reference and use a few precise style words.",
          "Ask for the format you want once, explicitly, to avoid reformat round-trips."],
      dont:["Don't re-explain the same standing context in every prompt.",
            "Don't rely on adjectives alone for images when one reference would settle it."] },
  ],

  // RULE BOOK — tag: always / default / avoid.
  rules: [
    { cat:"Video", tag:"always", if:"making a social reel, Short or TikTok", then:"cap it at 720p and about 5 seconds", why:"Vertical feeds re-compress hard. The extra pixels and seconds never reach the viewer — they just spend credits." },
    { cat:"Video", tag:"default", if:"the shot is near-static (talking head, product loop)", then:"skip the heavy motion presets", why:"Motion presets cost more and add nothing to a subject that isn't really moving." },
    { cat:"Video", tag:"default", if:"you want a cinematic feel", then:"use exactly one camera move, not stacked ones", why:"One clean push or orbit reads better — and costs less — than three presets fighting each other." },
    { cat:"Video", tag:"always", if:"your start frame is noisy or low-res", then:"fix the frame before you generate", why:"Motion amplifies whatever's already there. A weak frame guarantees a paid re-roll." },
    { cat:"Video", tag:"avoid", if:"tempted to render 10s 'to get more'", then:"render 5s and trim instead", why:"Duration multiplies the credit cost, usually for footage you cut anyway." },
    { cat:"Video", tag:"default", if:"the background is busy", then:"simplify or blur it first", why:"Complex backgrounds smear under motion and force retries." },

    { cat:"Image & Upscale", tag:"always", if:"upscaling a real photo you want to stay faithful", then:"keep Creativity low and Resemblance high", why:"High creativity invents detail that wasn't there, which sends you into re-runs." },
    { cat:"Image & Upscale", tag:"always", if:"the source has JPEG noise or artifacts", then:"clean it before upscaling", why:"Upscaling magnifies flaws, it doesn't remove them." },
    { cat:"Image & Upscale", tag:"always", if:"choosing an upscale factor", then:"pick it from your real output size, not the maximum", why:"8x-16x past the crop you'll actually publish is pure waste." },
    { cat:"Image & Upscale", tag:"default", if:"re-imagining an illustration at higher res", then:"treat 4x with higher Creativity as the ceiling worth paying for", why:"Past 4x rarely changes the crop you end up shipping." },
    { cat:"Image & Upscale", tag:"avoid", if:"an image has already been upscaled once", then:"don't upscale it again", why:"Errors compound across passes — you pay more for a worse result." },
    { cat:"Image & Upscale", tag:"default", if:"generating a marketing or hero image", then:"attach one reference image", why:"A reference does what ten adjectives can't, cutting the regenerations that quietly burn credits." },
    { cat:"Image & Upscale", tag:"avoid", if:"the result is close but the dimensions are wrong", then:"set the size up front next time rather than re-rolling", why:"Re-rolling to fix size pays full price for a framing tweak." },

    { cat:"Text & Reasoning", tag:"always", if:"the task is routine (draft, summarize, rephrase, classify)", then:"use the fast/cheap tier", why:"Routine text doesn't need a frontier model. The cheap tier is roughly 10-20x less per token for the same result." },
    { cat:"Text & Reasoning", tag:"always", if:"the task is genuinely hard (math, architecture, a tricky bug)", then:"use the top tier", why:"This is the one place to pay up. A cheap model that fails drops you into a retry loop that costs more overall." },
    { cat:"Text & Reasoning", tag:"default", if:"doing everyday coding (refactors, tests, small changes)", then:"default to the balanced tier", why:"Most coding lands first-try without the top tier; reserve that for the hard problems." },
    { cat:"Text & Reasoning", tag:"always", if:"working with large context you'll reuse across turns", then:"turn on prompt caching", why:"Caching stops you re-paying for the same document on every single message." },
    { cat:"Text & Reasoning", tag:"avoid", if:"you keep re-pasting the same document each turn", then:"cache or reference it instead", why:"Every re-paste is full-price tokens for context the model already had." },
    { cat:"Text & Reasoning", tag:"always", if:"generating many short outputs in bulk", then:"use the cheapest capable model and batch the calls", why:"Volume multiplies every inefficiency — this is where waste compounds fastest." },

    { cat:"Prompts & Tokens", tag:"always", if:"a prompt carries politeness or preamble", then:"cut it", why:"It's tokens going in and tokens echoed back, for zero quality gain." },
    { cat:"Prompts & Tokens", tag:"default", if:"you can show an example of what you want", then:"show one instead of describing the format at length", why:"An example is denser and clearer than a paragraph about it." },
    { cat:"Prompts & Tokens", tag:"always", if:"you have standing rules or context", then:"put them in a system / custom-instruction slot", why:"So you state them once instead of in every message." },
    { cat:"Prompts & Tokens", tag:"always", if:"compressing a prompt", then:"protect the instructions, constraints, examples and data", why:"Over-cutting causes a re-run that costs more than every token you saved. Shorter is not the goal — right-sized is." },
    { cat:"Prompts & Tokens", tag:"default", if:"using aggressive / telegraphic compression", then:"re-read it before sending", why:"Stripped-down prompts can drift into ambiguity the model fills in wrong." },
    { cat:"Prompts & Tokens", tag:"default", if:"pasting a whole file or chat history", then:"paste only the relevant slice", why:"The model rarely needs all of it, and you pay for every line." },

    { cat:"Every tool", tag:"always", if:"a cheaper setting looks identical in the final medium", then:"use the cheaper setting", why:"The whole game in one rule: spend only where the viewer or reader can actually tell." },
    { cat:"Every tool", tag:"default", if:"you're unsure what a setting costs", then:"test once small before a batch run", why:"One cheap probe beats discovering the cost across fifty outputs." },
    { cat:"Every tool", tag:"default", if:"a tool offers a 'max' preset", then:"treat max as a ceiling, not a default", why:"Maximums are there for the rare case that needs them, not for every job." },
    { cat:"Every tool", tag:"always", if:"the model lineup or pricing has changed", then:"re-verify these rules", why:"This space moves fast; a rule that saved credits last month can be stale today." },
  ],
};
